### ISSUE TITLE
I cannot connect to monitoring.[aws_region].amazonaws.com 

### ISSUE THREAD

**Issue by ukozaa** [mobarrio/cloudwatch_wrapper#3]
Hi,

Thank you for your instruction. It works well.
Until I run docker container on our server behind proxy. 
I cannot connect to monitoring.[aws_region].amazonaws.com on docker container because it couldn't call to this url via our proxy. 

![image](https://user-images.githubusercontent.com/7532020/195308670-70a374f1-87db-47ab-acb1-f123fd39cb6a.png)

So, How can I solve for this issue?

Regards.
Sarun

**Comment by mobarrio** [comment]
Hi Okuzaa,
    you can try changing the httpOptions timeout from the SDK configuration. 
Do you have a direct connection to AWS or do you go through a proxy? If so, you may need to configure the proxy option. 

AWS.config.update({httpOptions: {timeout: 360000}});

![image](https://user-images.githubusercontent.com/1693682/195407615-3eb27684-fddb-44cf-97de-6831a55db707.png)

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#constructor-property

Mariano

**Comment by mobarrio** [comment]
Hi again, do you have a new image (0.0.13) in dockerhub with these changes.

![image](https://user-images.githubusercontent.com/1693682/195418925-daa0949c-dae5-4297-b4ca-b47d2c46d1b4.png)

![image](https://user-images.githubusercontent.com/1693682/195419067-da8cfc58-fbef-4868-8fde-ce0429d8ab6f.png)

Mariano

**Comment by ukozaa** [comment]
> 

Thank you for your reply, unfortunately I must access to AWS through a proxy. But when I try to add proxy to my docker container it didn't route to proxy server anyway it go to AWS directly. I don't know why. It may add proxy configuration it your code or not?

**Comment by ukozaa** [comment]
> > 
> 
> Thank you for your reply, unfortunately I must access to AWS through a proxy. But when I try to add proxy to my docker container it didn't route to proxy server anyway it go to AWS directly. I don't know why. It may add proxy configuration it your code or not?

OK, After I read your message carefully. Now I can access to AWS via proxy by use proxy-agent package already.
Thank you for your suggestion.

Regards,
Sarun
